num1=float(input())
num2=int(input())
num1str=str(num1)
num2str=str(num2)
soma=num1+num2
concatenacao=num1str+num2str
multiplicacao=num1*num2
multiplicacao_string=num1str*num2
divisao=num1/num2
divisao_inteira=num1//num2
exponenciacao=num1**num2
resto=num1%num2
print(soma)
print(concatenacao)
print(multiplicacao)
print(multiplicacao_string)
print(divisao)
print(divisao_inteira)
print(exponenciacao)
print(resto)
