altura=int(input())
comprimento=int(input())
largura=int(input())
a_piso=largura*comprimento
v_sala=largura*comprimento*altura
a_parede=2*altura*largura+2*altura*comprimento
print(a_piso)
print(v_sala)
print(a_parede)
